services:
  postgres:
    image: postgres:16-alpine
    container_name: splitt-postgres
    environment:
      POSTGRES_USER: splitt
      POSTGRES_PASSWORD: splitt
      POSTGRES_DB: splitt
    ports:
      - "5434:5432"
    volumes:
      - splitt-postgres-data:/var/lib/postgresql/data

volumes:
  splitt-postgres-data:
